### ISSUE TITLE
Status codes for POST request

### ISSUE THREAD

**Issue by FoldiKrizsanIldiko** [EviBera/adopt-a-pet#5]
1. **Title**: Status code for POST request
2. **Description**: The POST request to the API endpoint `/api/advertisement` is returning a 200 OK status code instead of the expected 201 Created status code. According to the HTTP specification, a successful POST request that results in the creation of a new resource should return a 201 status code.
3. **Steps to Reproduce**:  POST /api/advertisement
                                            Request body : {
                                                                     "petId": 1,
                                                                      "expiresAt": "2024-07-13T08:35:33.839Z"
                                                                     }

5. **Expected Behavior**: Expected is to get 201 Created status code
6. **Actual Behavior**: Got 200 OK status code, and response body : {
    "id": 14,
    "petDto": {
        "id": 1,
        "name": "Whiskers",
        "species": "Cat",
        "birth": "2022-12-25T00:00:00Z",
        "gender": "Male",
        "isNeutered": true,
        "description": "Playful and affectionate Domestic Shorthair cat. Adaptable and thrives in most households.",
        "ownerId": "",
        "pictureLink": "https://lh3.googleusercontent.com/u/0/drive-viewer/AKGpihZHkIHKVx7e9wzZfVln6QKLdoHo7OOrSo_RXIjTzR0lFK9AAK-LqpvRFZRUhl0HAWUqlSw2MtP3Eksa0egyK3p3gkUgCTleEZo=w1110-h911-rw-v1"
    },
    "createdAt": "2024-07-15T12:46:16.2545025Z",
    "expiresAt": "2024-07-15T12:46:16.167Z",
    "applications": []
}
7. **Screenshots/Logs**:  
![image](https://github.com/user-attachments/assets/c940aaaf-6c70-44f0-8011-7377ef54cfc4)

8. **Additional Information**: Getting 200 OK status code for POST request tipically means that the server processed the request successfully, but it might not be explicitly stating that a new resource was created.
 201 Created statuts code for POST request specifically used when a new resource has been created as a result of the request.
10. **Possible Solution**: For all Post request sending 201 Created status code

**Comment by EviBera** [comment]
Status codes updated
